const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/api.route',]

const doc = {
    info: {
        version: "1.0.0",
        title: "Neehar - Neuro",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    // host: "13.53.215.119:7071",
    host: "localhost:7071",
    // host: 'nodejs-projects-swagruhabackend.un7jm4.easypanel.host',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [{
        "name": "Neehar Neuro",
        "description": "API for Neehar Neuro portal"
    }],   
    basePath: '/api',
    securityDefinitions: {
        bearerAuth:{
            type: 'apiKey',
            name: 'authorization',
            scheme: 'bearer',
            in: 'header',
            "description":"Ex: Bearer 14213841804v323v3...."
        },
    },
    security: { bearerAuth: [] }
}

swaggerAutogen(outputFile, endpointsFiles,doc)